development:
  adapter: postgresql
  encoding: unicode
  database: nutritionappseperated_dev
  pool: 5
  username: nutritionappseperated
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: nutritionappseperated_test
  pool: 5
  username: nutritionappseperated
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: nutritionappseperated_production
  pool: 5
  username: nutritionappseperated
  password: password